baseURL = "https://www.lesgaragesnumeriques.com/"
languageCode = "en-US"
title = "Les Garages Numériques"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    description = "Digital arts festival - 7-11/11 - La Bourse Brussels"
    author = "Studio Colibri"
